### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mchapiro1**
I'd like to add an article I wrote on energy with a perspective that is missing from the rest of the literature. https://astigmatic.substack.com/p/bitcoin-is-the-energy-minimal-system

In addition to it being free / openly available now, I will never be paywalling this newsletter (I'll probably never paywall anything as I'm largely averse to the concept).

### CODE REVIEW

**Comment by pox** [comment]
Thanks. It was already proposed in PR #13

**Comment by pox** [comment]
@mchapiro1 I've replied in issue #13. 

My apologies for not adding your article to the page just yet.

**Comment by mchapiro1** [comment]
Thanks! Sorry for double request. I'm not familiar with GitHub and it was
only after I figured out how to do the pull request that I saw someone I
had asked for help had already entered one.

**Comment by pox** [comment]
For the record, this is what top-quality content looks like: https://www.swanbitcoin.com/bitcoins-energy-usage-is-not-a-problem-heres-why-by-lyn-alden/

Not half-edited ramblings accompanied by trash talking on Twitter when your post does't get included.

**Pull request closed without merging**
